version: "3"
services:
  web:
    container_name: web
    build: ./docker/web
    ports:
      - "8083:80"
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - app

  app:
    container_name: app
    build: ./docker/app
    volumes:
      - ./src:/var/www/src
    working_dir: /var/www/src
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3303
      - DB_DATABASE=${DB_NAME:-laravel_local}
      - DB_USERNAME=${DB_USER:-phper}
      - DB_PASSWORD=${DB_PASS:-secret}

    depends_on:
      - db

  db:
    container_name: db
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${DB_NAME:-laravel_local}
      - MYSQL_USER=${DB_USER:-phper}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}
    ports:
      - "3303:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
